language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 target_branch: production-branch
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master