language: node_js
node_js:
 - 17

cache: npm

script: npm run build

sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

deploy:
 provider: pages
 target_branch: production-branch
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master