language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t lulbricht179/homepage-cv -f Dockerfile.dev .

deploy:
 provider: pages
 app: "docker"
 env: "Docker-env"
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: main