version: '3'
services:
  vue:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true